---
extends: eslint:recommended
parserOptions:
  ecmaVersion: 6
  sourceType: script
env:
  es6: true
  jasmine: true
  node: true
rules:
  linebreak-style:
  - error
  - unix
  semi:
  - error
  - always
  space-before-function-paren:
  - error
  - anonymous: always
    named: never
    asyncArrow: always
  prefer-const:
  - warn
  no-tabs:
  - error
  indent:
  - error
  - 2
  - SwitchCase: 1
  block-spacing:
  - error
  - always
  brace-style:
  - error
  - 1tbs
  - allowSingleLine: true
  comma-dangle:
  - error
  - never
  comma-spacing:
  - error
  - before: false
    after: true
  comma-style:
  - error
  - last
  - exceptions: { ArrayExpression: true, ObjectExpression: true }
  computed-property-spacing:
  - error
  - never
  eol-last:
  - error
  - always
  func-call-spacing:
  - error
  - never
  func-style:
  - error
  - declaration
  - allowArrowFunctions: true
  key-spacing:
  - error
  - beforeColon: false
    afterColon: true
    mode: strict
  keyword-spacing:
  - error
  - before: true
    after: true
  max-depth:
  - warn
  - 8
  max-len:
  - warn
  - 220
  max-nested-callbacks:
  - warn
  - 5
  no-trailing-spaces:
  - warn
  semi-spacing:
  - error
  space-before-blocks:
  - error
  space-infix-ops:
  - error
  space-unary-ops:
  - error
  spaced-comment:
  - warn
  - always
  no-var:
  - error
  no-unused-vars:
  - warn


